export const products = [
    {
        id: "1",
        name: "Filamento PLA 1.75mm",
        category: "filamentos",
        description: "Filamento PLA de alta calidad, ideal para impresiones precisas y resistentes.",
        price: 20.99,
        stock: 50,
    },
    {
        id: "2",
        name: "Filamento ABS 1.75mm",
        category: "filamentos",
        description: "Filamento ABS resistente a altas temperaturas, color negro.",
        price: 22.99,
        stock: 40,
    },
    {
        id: "3",
        name: "Impresora 3D Ender 3 V2",
        category: "impresoras",
        description: "Impresora 3D económica y versátil con cama caliente y pantalla mejorada.",
        price: 220.0,
        stock: 10,
    },
    {
        id: "4",
        name: "Impresora 3D Creality CR-10",
        category: "impresoras",
        description: "Impresora de gran volumen de impresión, ideal para proyectos grandes.",
        price: 350.0,
        stock: 5,
    },
    {
        id: "5",
        name: "Kit de boquillas 0.4mm",
        category: "accesorios",
        description: "Pack de 5 boquillas de latón de 0.4mm para impresoras 3D de extrusión directa.",
        price: 12.5,
        stock: 30,
    },
    {
        id: "6",
        name: "Resina para impresión 3D",
        category: "resinas",
        description: "Resina de alta precisión para impresoras SLA/DLP, color gris.",
        price: 35.99,
        stock: 20,
    },
    {
        id: "7",
        name: "Cama de vidrio templado",
        category: "accesorios",
        description: "Placa de vidrio templado para impresoras 3D, compatible con Ender 3 y similares.",
        price: 15.0,
        stock: 25,
    },
    {
        id: "8",
        name: "Spray adhesivo para cama caliente",
        category: "accesorios",
        description: "Spray adhesivo para mejorar la adhesión de las primeras capas en impresoras 3D.",
        price: 8.5,
        stock: 100,
    },
    {
        id: "9",
        name: "Boquilla de acero endurecido 0.4mm",
        category: "accesorios",
        description: "Boquilla de acero endurecido, ideal para filamentos abrasivos como carbono o fibra de vidrio.",
        price: 25.99,
        stock: 10,
    },
];
